# Generated by Django 3.2.16 on 2022-11-28 23:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('condition', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_desc', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodium', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('potassium', models.IntegerField(default=0)),
                ('phosphorus', models.IntegerField(default=0)),
                ('food', models.ManyToManyField(blank=True, to='kidney_app.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Journal_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('meal_category', models.CharField(max_length=25)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidney_app.account')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='journal_entry',
            field=models.ManyToManyField(blank=True, to='kidney_app.Journal_Entry'),
        ),
    ]
